#! /bin/bash

# The lock file, because we want only one instance of HipChat
LOCKFILE=${XDG_RUNTIME_DIR}/HipChat.lock
LOCKFD=99

_lock()             { flock -$1 ${LOCKFD}; }
_prepare_locking()  { eval "exec ${LOCKFD}>\"${LOCKFILE}\""; }
exlock_now()        { _lock xn; }
exlock()            { _lock x; }
shlock()            { _lock s; }
unlock()            { _lock u; }

if [ -n "$STY" ] ; then

	# Ensure we have only one copy of HipChat running
	_prepare_locking
	exlock_now || {
		# There is another HipChat running - switch to it
		wmctrl -i -R $(wmctrl -l | grep "N/A HipChat" | head -1 | cut -d ' ' -f 1)
		exit 0
	}

	# Set default server for first time launchers
	if [ ! -d ~/.config/Atlassian ] ; then
		mkdir -p ~/.config/Atlassian
		echo "force_server=https://chat.corp.badoo.com" > ~/.config/Atlassian/config.ini
	fi

	# Some magic to run hipchat maximized and with a correct hidpi zoom
	if [ -r ~/.config/Atlassian/HipChat.ini ] ; then
		sed -i -e 's/^windowMaximized=false$/windowMaximized=true/' \
			-e 's/^zoomFactor=.*/zoomFactor=2.5/' \
			~/.config/Atlassian/HipChat.ini
	fi

	# Run the HipChat
	docker run -ti --rm --name hipchat4 \
		--device /dev/dri --device /dev/snd \
		--net host --hostname docker \
		-e DISPLAY=unix${DISPLAY} \
		-e QT_AUTO_SCREEN_SCALE_FACTOR=1 \
		-v ${HOME}:${HOME} \
		-v /etc/localtime:/etc/localtime:ro \
		-v ${HOME}/.icons/default:/usr/share/icons/Adwaita:ro \
		-v /etc/machine-id:/etc/machine-id:ro \
		-v /var/run/dbus:/var/run/dbus \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		-w ~/.config/Atlassian \
		anight/hipchat4 \
		/opt/HipChat4/bin/HipChat4 $@

else
	# Run the code above in screen session
	screen -dmS HipChat $0 $@
fi

